<?php

/*

Page: /dp/article_add.php

Error: MySQL server has gone away <br />Error sql: <font color='red'>Select ispart,channeltype From `dede_arctype` where id='20' limit 0,1;</font>

*/

?>

<?php

/*

Page: /plus/count.php?view=yes&aid=114&mid=2

Error: DedeEIMS错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

/*

Page: /plus/count.php?view=yes&aid=114&mid=2

Error: DedeEIMS错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

/*

Page: /plus/count.php?view=yes&aid=112&mid=2

Error: DedeEIMS错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: Table 'dpoxx.dede_test' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM dede_test</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE term_id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE term_id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE term_id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE term_id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE term_id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE term_id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE term_id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE term_id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: No database selected <br />Error sql: <font color='red'>SELECT * FROM wp_terms WHERE term_id = 1 limit 0,1;</font>

*/

?>

<?php

die('Request Error!');

/*

Page: /api/api.php

Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>

*/

?>

<?php
die('Request Error!');
/*
Page: /test/api/api.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
